import Foundation

extension Notification.Name {
    static let imageCanvasAddImages = Notification.Name("imageCanvasAddImages")
    static let imageCanvasOpenFolder = Notification.Name("imageCanvasOpenFolder")
    static let imageCanvasNewBoard = Notification.Name("imageCanvasNewBoard")
    static let imageCanvasToggleChrome = Notification.Name("imageCanvasToggleChrome")
    static let imageCanvasToggleDrawingMode = Notification.Name("imageCanvasToggleDrawingMode")
    static let imageCanvasDisableDrawingMode = Notification.Name("imageCanvasDisableDrawingMode")
    static let imageCanvasToggleTextMode = Notification.Name("imageCanvasToggleTextMode")
    static let imageCanvasClearDrawings = Notification.Name("imageCanvasClearDrawings")
    static let imageCanvasApplyFolderUpdate = Notification.Name("imageCanvasApplyFolderUpdate")
    static let imageCanvasTakeSnapshot = Notification.Name("imageCanvasTakeSnapshot")
    static let imageCanvasShowSnapshotSettings = Notification.Name("imageCanvasShowSnapshotSettings")
    static let imageCanvasSnapshotProgress = Notification.Name("imageCanvasSnapshotProgress")
    static let imageCanvasNotice = Notification.Name("imageCanvasNotice")
    static let imageCanvasCheckForUpdates = Notification.Name("imageCanvasCheckForUpdates")

    static let imageCanvasFitAll = Notification.Name("imageCanvasFitAll")
    static let imageCanvasZoomIn = Notification.Name("imageCanvasZoomIn")
    static let imageCanvasZoomOut = Notification.Name("imageCanvasZoomOut")
    static let imageCanvasSelectAll = Notification.Name("imageCanvasSelectAll")
    static let imageCanvasRemoveSelected = Notification.Name("imageCanvasRemoveSelected")
    static let imageCanvasRotateSelected = Notification.Name("imageCanvasRotateSelected")
    static let imageCanvasRotateSelectedCounterclockwise = Notification.Name("imageCanvasRotateSelectedCounterclockwise")
    static let imageCanvasFlipHorizontal = Notification.Name("imageCanvasFlipHorizontal")
    static let imageCanvasFlipVertical = Notification.Name("imageCanvasFlipVertical")
    static let imageCanvasRevealSelectedInFinder = Notification.Name("imageCanvasRevealSelectedInFinder")
    static let imageCanvasArrangePicasa = Notification.Name("imageCanvasArrangePicasa")
    static let imageCanvasArrangeNativeTiled = Notification.Name("imageCanvasArrangeNativeTiled")
    static let imageCanvasArrangePinterest = Notification.Name("imageCanvasArrangePinterest")
    static let imageCanvasUndo = Notification.Name("imageCanvasUndo")
    static let imageCanvasRedo = Notification.Name("imageCanvasRedo")
    static let imageCanvasRedoDrawing = Notification.Name("imageCanvasRedoDrawing")
}
